# Generated by Django 5.0.7 on 2024-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_collegeportal_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeportal',
            name='email_students',
            field=models.JSONField(default=list),
        ),
    ]
