# Generated by Django 5.0.7 on 2024-08-24 03:58

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=Home.models.generate_short_uuid, editable=False, max_length=10, unique=True),
        ),
    ]
